version: "3"
services:
  example_local_db:
    image: postgres:11.5-alpine
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgresroot
      POSTGRES_DB: example_test
    volumes:
      - "./dbdata:/var/lib/postgresql/data"
